sudo: required
services:
  - docker

before_install:
  - docker build -t charanreddy2646/docker-react -f Dockerfile.dev .

script:
  - docker run charanreddy2646/docker-react npm run test -- --coverage