version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /Users/srija/Desktop/redis/visits/node_modules
      - .:/Users/srija/Desktop/redis/visits/
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /Users/srija/Desktop/redis/visits/node_modules
      - .:/Users/srija/Desktop/redis/visits/
    command: ["npm", "run", "test"]
